name: Multi-File Code Review with Ollama

on:
  push:
    branches:
      - main

jobs:
  ollama-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start Ollama container
        run: |
          docker run -d -p 11434:11434 --name ollama ollama/ollama
          ollama pull mistral
          sleep 20
      - name: Pull Mistral model
        run: |
          curl -s http://localhost:11434/api/pull -d '{"name": "mistral"}'
          sleep 10

      - name: Prepare review prompt for multiple files
        run: |
          echo "You are expert in code reviewing." > prompt.txt
          echo "" >> prompt.txt
          echo "Please review the following code files:" >> prompt.txt
          echo "" >> prompt.txt

          # Exclude prompt.txt from being included in the review
          for file in $(find . -type f \( -name "*.py" -o -name "*.txt" -o -name "Dockerfile" \) ! -name "prompt.txt"); do
            echo "===== File: $file =====" >> prompt.txt
            cat "$file" >> prompt.txt
            echo -e "\n\n" >> prompt.txt
          done

          echo "Perform the following tasks:" >> prompt.txt
          echo "1. Identify any bugs or potential issues." >> prompt.txt
          echo "2. Detect any security vulnerabilities or bad practices." >> prompt.txt
          echo "3. Suggest improvements for performance, readability, or maintainability." >> prompt.txt
          echo "4. Suggest unit test cases that should be written for this code, including edge cases." >> prompt.txt
          echo "5. Finally, state whether this code is ready to be committed to Git or if changes are required." >> prompt.txt

      - name: Run code review with Ollama
        run: |
          cat prompt.txt
          # Safely read prompt and encode it as JSON
          encoded_prompt=$(jq -Rs . < prompt.txt)

          # Write JSON payload to a file
          echo "{\"model\": \"mistral\", \"prompt\": $encoded_prompt}" > payload.json

          # Send request to Ollama
          curl -s -X POST http://localhost:11434/api/generate \
            -H "Content-Type: application/json" \
            -d @payload.json > review.txt

          echo "=== Code Review Output ==="
          cat review.txt

      - name: Upload Review Output
        uses: actions/upload-artifact@v4
        with:
          name: ollama-review
          path: review.txt
